// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"HIME_PreTitleEvents","status":true,"description":"Build your own sequence of events that should occur before\r\nthe title screen begins","parameters":{"Pre-Title Map ID":"1","Use As Title":"false"}},
{"name":"Galv_ScreenZoom","status":true,"description":"(v.1.1) Zoom in on a certain part of the screen","parameters":{"Battle Zoom":"1"}},
{"name":"more_character_frames_(mv)","status":true,"description":"Allows more than 3 Frames","parameters":{}},
{"name":"OrangeRegionCollisions","status":true,"description":"Allows the usage of regions to overwrite the passability configuration of tiles","parameters":{"BlockRegionId":"1","UnblockRegionId":"0","BlockPlayerRegionId":"0","UnblockPlayerRegionId":"0","BlockEventRegionId":"0","UnblockEventRegionId":"0"}},
{"name":"GALV_DisableDash","status":true,"description":"Disable dash in your game.","parameters":{"Disable Option":"true"}},
{"name":"QPlus","status":true,"description":"<QPlus> (Should go above all Q Plugins)\r\nSome small changes to MV for easier plugin development.","parameters":{"Quick Test":"true","Default Enabled Switches":"[]","Ignore Mouse when inactive":"false"}},
{"name":"QInput","status":true,"description":"<QInput>\nAdds additional keys to Input class, and allows remapping keys.","parameters":{"Threshold":"0.5","Input Remap":"","Ok":"[\"#enter\", \"#space\", \"#z\", \"$A\"]","Escape / Cancel":"[\"#esc\", \"#insert\", \"#x\", \"#num0\", \"$B\"]","Menu":"[\"#esc\", \"$Y\"]","Shift":"[\"#shift\", \"#cancel\", \"$X\"]","Control":"[\"#ctrl\", \"#alt\"]","Tab":"[\"#tab\"]","Pageup":"[\"#pageup\",\"$L1\"]","Pagedown":"[\"#pagedown\",\"$R1\"]","Left":"[\"#left\", \"#num4\", \"$LEFT\"]","Right":"[\"#right\", \"#num6\", \"$RIGHT\"]","Up":"[\"#up\", \"#num8\", \"$UP\"]","Down":"[\"#down\", \"#num2\", \"$DOWN\"]","Debug":"[\"#f9\"]","ControlKeys Remap":"","FPS":"f2","Streched":"f3","FullScreen":"f4","Restart":"f5","Console":"f8"}},
{"name":"CmdInp","status":true,"description":"v1.1.2 CmdInp Enables a Command Input system.","parameters":{"Text Variable":"1","Max Characters":"16","Use Image":"false","Image Name":"ClipComputer","Default Header":"","Default InputText":""}},
{"name":"Galv_PixelMove","status":true,"description":"(v.1.0) Gives the illusion of pixel movement for the player.","parameters":{"Diagonal Speed":"90","Diagonal Charset":"false","Tile Delay":"30"}}
];
